<a href="https://colab.research.google.com/github/PutuRama/colab-project/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:


data(state)
state.x77 <- data.frame(state.x77)

state.x77$grpPop <- cut(state.x77$Population, breaks = c(0,3000, 10000, Inf), labels = c("low", "medium", "high"))
state.x77$grpInc <- ifelse(state.x77$Income <= median(state.x77$Income), "low", "high")
state.x77$grpFrost <- cut(state.x77$Frost, breaks = quantile(state.x77$Frost, c(0, 0.25, 0.5 , 0.75, 1)), labels = c("hot", "warm", "chill", "cold"))

head(state.x77)
dim(state.x77)
paste("Mean: ", mean(state.x77$Illiteracy))
paste("Median: ", median(state.x77$Life.Exp))
# quantile(state.x77$Life.Exp, c(0.25, 0.50, 0.75, labels = c("Quantiile")))
which.max(state.x77$Income)
rownames(state.x77$Income)[which.max(state.x77$Income)]
# table(state.x77$grpPop, state.x77$grpInc)
# ftable(state.x77$grpInc, state.x77$grpPop, state.x77$grpFrost)

# tab1 <- table( state.x77$grpPop, state.x77$grpFrost)
# prop.table(tab1, 2)

# summary(state.x77)


Population Income Illiteracy Life.Exp Murder HS.Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766
           grpPop grpInc grpFrost
Alabama    medium low    hot     
Alaska     low    high   cold    
Arizona    low    high   hot     
Arkansas   low    low    hot     
California high   high   hot     
Colorado   low    high   cold

[1] 50 11

[1] "Mean:  1.17"

[1] "Median:  70.675"

[1] 2

NULL

In [ ]:
student_names <- c("Nathan", "Ananda","Rian" , "Rangga")
student_ages <- c(18, 30,90 , 19)
student_scores <- c(85, 85,69 , 90)
student_passed <- c(TRUE, TRUE,FALSE , TRUE)

my_dataset <- data.frame(
  Name = student_names,
  Age = student_ages,
  Grade = student_scores,
  Passed = student_passed
)

print(my_dataset)

summary(my_dataset)

    Name Age Grade Passed
1 Nathan  18    85   TRUE
2 Ananda  30    85   TRUE
3   Rian  90    69  FALSE
4 Rangga  19    90   TRUE


     Name                Age            Grade         Passed       
 Length:4           Min.   :18.00   Min.   :69.00   Mode :logical  
 Class :character   1st Qu.:18.75   1st Qu.:81.00   FALSE:1        
 Mode  :character   Median :24.50   Median :85.00   TRUE :3        
                    Mean   :39.25   Mean   :82.25                  
                    3rd Qu.:45.00   3rd Qu.:86.25                  
                    Max.   :90.00   Max.   :90.00                  

In [ ]:
  # v <- seq(from = 1, to = 100, by = 20)
  # v

  # x <- rep(c("Highest","High", "Medium", "Low", "Lowest"), times=10)
  # x <- factor(x)
  # x

  # y <-factor(1:3, labels =c("Indra", "Rian", "Ananda"))
  # y

  # matriks1 <- matrix(c(1,2,4,6,7,8,9,11,0), nrow = 3, ncol = 3)
  # matriks2 <- matrix(9:17, nrow = 3, ncol = 3)
  # matriks <- matriks1 * matriks2
  # matriks
  # t(matriks)
  # diag(matriks)

  # Pokemon List
  bst<-factor(1:10, labels = c(253, 325, 425, 249, 325, 425, 250, 325, 425, 175))
  pkmn<-factor(1:10, labels = c("Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Watortle", "Blastoise", "Caterpie"))
  ten_pokemon <- data.frame(ID = 1:10, bst,pkmn, sex=rep(c("Male", "Female")))
  ten_pokemon
  search_term <- readline(prompt = "Search on the table: ")
  matching_rows <- rowSums(apply(ten_pokemon, 2, function(col) grepl(search_term, col, ignore.case = TRUE)))>0
  advanced_search_results <- ten_pokemon[matching_rows, ]
  advanced_search_results

ID bst pkmn       sex   
1   1 253 Bulbasaur  Male  
2   2 325 Ivysaur    Female
3   3 425 Venusaur   Male  
4   4 249 Charmander Female
5   5 325 Charmeleon Male  
6   6 425 Charizard  Female
7   7 250 Squirtle   Male  
8   8 325 Watortle   Female
9   9 425 Blastoise  Male  
10 10 175 Caterpie   Female

Search on the table: 325


ID bst pkmn       sex   
2 2  325 Ivysaur    Female
5 5  325 Charmeleon Male  
8 8  325 Watortle   Female

In [ ]:
vec <- c()
loop <- 1

for (x in 1:9)
{
  input_num <- readline()
  input_num <- as.numeric(input_num)
  vec[loop] <- input_num
  loop <- loop + 1
}
  matrik <- matrix(vec, nrow = 3, ncol = 3)
  print(matrik)
  paste("DETERMINAN: ",det(matrik) )
  print("INVERS")
  solve(matrik)
  print("TRANSPOSE")
  t(matrik)
  print("DIAGONAL")
  diag(matrik)

0
9
1
2
3
3
1
5
6
     [,1] [,2] [,3]
[1,]    0    2    1
[2,]    9    3    5
[3,]    1    3    6


[1] "DETERMINAN:  -74"

[1] "INVERS"


[,1]        [,2]        [,3]       
[1,] -0.04054054  0.12162162 -0.09459459
[2,]  0.66216216  0.01351351 -0.12162162
[3,] -0.32432432 -0.02702703  0.24324324

[1] "TRANSPOSE"


[,1] [,2] [,3]
[1,] 0    9    1   
[2,] 2    3    3   
[3,] 1    5    6

[1] "DIAGONAL"


[1] 0 3 6

In [115]:
quantile(state.x77$Illiteracy, c(0.25, 0.5))

25%   50% 
0.625 0.950